
# -------- Pods init

# Disable all warnings in pods so the build is clean
inhibit_all_warnings! 

# Define CP Specs source
#source 'https://github.com/CocoaPods/Specs.git'

# Force iOS10+ platform
platform :ios, '10.0'

# Swift frameworks
use_frameworks!


def core_pods
# -------- Frameworks / Networking

pod 'Alamofire' => '4.0'
pod 'Warp'


# -------- Frameworks / Data storage



# -------- Frameworks / UI

pod "HanekeSwift", :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'


# -------- Frameworks / Utilities
end

target 'Laurine' do
   core_pods
end




